todoapi/urls.py
from django.urls import path
from . import views

app_name = 'todoapi'
urlpatterns = [
    path('todos/', views.get_todos),
    path('todos/create/', views.post_todos),
    path('todos/<int:id>', views.put_and_delete_todos)
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todos.urls',namespace='todos')),
    path('api/', include('todoapi.urls', namespace='todoapi')),
    path('accounts/', include('django.contrib.auth.urls'))
]

todos/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'todos'
#urlconfig
urlpatterns = [
    path('hello/', views.say_hello),
    path('', views.todos_list, name='todo_list'),
    path('form/', views.todo_form, name='todo_form'),
    path('accounts/login/', views.MyLoginView.as_view(), name='login'),
    path('accounts/logout/', views.MyLogoutView.as_view(), name='logout')
]

todoapi/models.py
from django.db import models

# Create your models here.

todos/models.py
from django.db import models
import random
# Create your models here.

class userProfile(models.Model):
    name = models.CharField(max_length=20, default="user")

    def __str__(self):
        return self.name
class Todo_Entity(models.Model):
    title = models.CharField(max_length=20)
    description = models.CharField(max_length=400)
    done = models.BooleanField(default=False)
    createdAt = models.DateTimeField()
    user = models.ForeignKey(userProfile, on_delete=models.CASCADE, default=random.randint(1, 10))

todos/forms.py
from django import forms
from .models import Todo_Entity
from .models import userProfile

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo_Entity
        fields = {'title','description','createdAt','user'}

    def __init__(self, *args, **kwargs):
        super(TodoForm,self).__init__(*args, **kwargs)
        self.fields['user'].empty_label = "Select User"

class UserForm(forms.ModelForm):
    class Meta:
        model = userProfile
        fields = '__all__'


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

# use tuple to provide fields if not all

todoapi/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from todos.models import Todo_Entity
from .serializers import TodoSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
# Create your views here.

@csrf_exempt
@api_view(['GET','POST'])
def get_todos(request):
    if request.method == "GET":
        todos = Todo_Entity.objects.all()
        serializer = TodoSerializer(todos, many=True)
        return JsonResponse({'todos':serializer.data})
    elif request.method == 'POST':
        serializer = TodoSerializer(data=request.data)
        serializer.initial_data['createdAt'] = timezone.now()
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
def post_todos(request):
    if request.method == 'POST':
        serializer = TodoSerializer(Todo_Entity, data=request.data)
        print(serializer)
        serializer.initial_data['createdAt'] = timezone.now()
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)


@api_view(['GET','PUT','DELETE'])
def put_and_delete_todos(request, id):
    try:
        todo =Todo_Entity.objects.get(pk=id)
    except:
        return Response(status=status.HTTP_400_BAD_REQUEST)

    if request.method == 'GET':
        serializer = TodoSerializer(todo)
        return  Response(serializer.data)
    elif request.method == 'PUT':
        serializer = TodoSerializer(todo, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        todo.delete()
        return JsonResponse({"message":"deleted successfully"},status=status.HTTP_204_NO_CONTENT)

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .forms import TodoForm
from .forms import UserForm
from .models import Todo_Entity
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

# Create your views here.
def say_hello(request):
    return HttpResponse("hello world")

def todos_list(request):
    if request.method == "GET":
        form = UserForm()
        context = {'todos': Todo_Entity.objects.all(),'form':form}
        return render(request, 'todos.html', context)
    else:
        status = request.POST.get('status')
        if status is not None:
            my_object = Todo_Entity.objects.get(id=status)
            if my_object.done == False:
                my_object.done = True
                my_object.save()
                return redirect('/')
            else:
                my_object.done = False
                my_object.save()
                return redirect('/')
        form = UserForm((request.POST))
        if form.is_valid():
            form.save()
        return redirect('/')


def todo_form(request):
    if request.method == "GET":
        form = TodoForm()
        return render(request, 'todo_form.html', {'form':form})
    else:
        form = TodoForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')
def todo_delete(request, id):
    myObject =get_object_or_404(Todo_Entity, id=id)
    myObject.delete()
    return redirect('/')

def todo_update_status(request):
    if request.method == "POST":
        status = request.POST.get('status')
        print(status + 1)
        return HttpResponse('yeah')

class MyLoginView(LoginView):
    template_name = 'registration/login.html'

class MyLogoutView(LogoutView):
    next_page = ('/')

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'todos:todo_form' %}">Create a Todo</a>
      </li>
        {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
        {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
        {% endif %}
      <li class="nav-item">
        <a class="nav-link disabled">Disabled</a>
      </li>
    </ul>
    <div class="container">
        <div class="col-md-10 offset-md-1 mt-5">
            <div class="jumbotron">
                <h1 class="display-4">Todo List</h1>
                <p class="lead-font-italic">todo app for implementing crud operations</p>
                <hr class="my-4">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</html>

todos/templates/todo_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>we will implement todolist creations here</h1>
<div>
    <form action="" method="post" autocomplete="off">
        {% csrf_token %}
        {{form.title|as_crispy_field}}
        {{form.description|as_crispy_field}}
        <div class="row">
            <div class="col-md-6">
                {{form.createdAt|as_crispy_field}}
            </div>
            <div class="col-md-6">
                {{form.user|as_crispy_field}}
            </div>
        </div>
        <div class="mt-4">
            <button type="submit" class="btn btn-success"><i class="fas fa-database"> Submit</i></button>
        </div>

    </form>
</div>
{% endblock content %}

todos/templates/todos.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Todos</h1>
<div>
     <table class="table table-borderless">
        <thead class="border-bottom font-weight-bold">
            <tr>
                <td><h2>Title</h2></td>
                <td><h2>Description</h2></td>
                <td><h2>User</h2></td>
                <td><h2>Done?</h2></td>
            </tr>
        </thead>
         <tbody>
            {% for todo in todos %}
                <tr>
                    <td>{{todo.title}}</td>
                    <td>{{todo.description}}</td>
                    <td>{{todo.user}}</td>
                    <td class="container row">
                        <form method="post" action="{% url 'todos:todo_list' %}">
                            {% csrf_token %}
                            <span class="col-sm-6">{{todo.done}}</span>
                            <input type="hidden" value='{{todo.id}}' name="status">
                            <button class="col-sm-6" type="submit" class="btn btn-success"><i class="fas fa-database"> change</i></button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
         </tbody>
     </table>
</div>
<div>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
         <div class="mt-4">
            <button type="submit" class="btn btn-success"><i class="fas fa-database"> Create a User</i></button>
        </div>
    </form>
</div>
{% endblock content %}